name: entorno
on:
  workflow_dispatch:


env:
  AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup secret
        run: echo "MY_SECRET_VALUE=${{ secrets['MY_SECRET_' + env.AMBIENTE] }}" >> $GITHUB_ENV

      - name: Shell
        run: |
          echo $AMBIENTE
          echo $MY_SECRET_VALUE

# env:
#   AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Shell
#         run: |
#           echo $AMBIENTE
#           echo ${{ secrets['MY_SECRET_' + env.AMBIENTE] }}


