name: entorno
on:
  workflow_dispatch:

env:
  AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Shell
        run: |
          echo $AMBIENTE
          echo ${{ secrets.MY_SECRET_${{ env.AMBIENTE }} }}
          echo ${{ vars.MY_VARIABLE_${{ env.AMBIENTE }} }}


