name: entorno
on:
  workflow_dispatch:

env:
  AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup secret name
        run: |
          echo "SECRET_NAME=MY_SECRET_${{ env.AMBIENTE }}" >> $GITHUB_ENV
          echo "VARIABLE_NAME=MY_VARIABLE_${{ env.AMBIENTE }}" >> $GITHUB_ENV

      - name: Use secret name
        run: |
          echo "Using secret name: $SECRET_NAME"
          echo "Using variable name: $VARIABLE_NAME"
          echo ${{ secrets[env.SECRET_NAME] }}
          echo ${{ vars[env.VARIABLE_NAME] }}


# env:
#   AMBIENTE: ${{ (github.ref == 'refs/heads/main' && 'dev') }}

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Shell
#         run: |
#           echo $AMBIENTE
#           echo ${{ secrets['MY_SECRET_' + env.AMBIENTE] }}


